"""Direct uploads from the agent's computer, covers from Drive, Drive listing.

The hosted server cannot read the user's files, and base64 through the model
context does not scale (one 300 KB JPEG is ~400K characters). So the bytes
never pass through the server or the model:

1. ``create_upload`` registers the files and returns presigned PUT URLs plus
   a ready-to-run bash script (curl);
2. the agent runs the script on the user's machine — it PUTs the bytes
   straight to storage and prints one JSON line;
3. ``complete_upload`` finishes the uploads with that JSON → ready Drive assets;
4. ``set_cover`` / ``set_covers`` use those assets as content covers.

Everything goes through the SDK's authenticated client (``_raw``), so these
tools do not depend on an unreleased SDK version.
"""

from __future__ import annotations

import math
import shlex
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import PurePath

import srg.exceptions
from mcp.types import ToolAnnotations

from srg_mcp import _raw
from srg_mcp._app import mcp
from srg_mcp._client import get_client

# Backend limit per POST /api/v1/assets/batch (CreateAssetsValidator).
_BATCH_LIMIT = 100
# Parallel file uploads in the generated script / parallel API calls here.
_SCRIPT_PARALLEL_FILES = 6
_API_WORKERS = 4
# A just-completed upload is marked ready in Content-Hub asynchronously; the
# cover-from-asset endpoint answers 400 "still uploading" until then.
_STILL_UPLOADING_RETRY_DELAYS = (1, 1, 2, 2, 3, 3, 4, 4, 5)

_MIN_PART_SIZE = 5 * 1024 * 1024
_MAX_PARTS = 10_000

_IMAGE_EXTS = {"jpg", "jpeg", "png", "gif", "bmp", "svg", "webp", "heic", "heif"}
_VIDEO_EXTS = {
    "4mv", "amv", "avi", "flv", "m4p", "m4v", "mkv", "mov", "mp4", "mpeg",
    "mpg", "mxf", "ogg", "ts", "vod", "webm", "wmv",
}  # fmt: skip


def _part_size(file_size: int) -> int:
    """Part size for a multipart upload (mirrors the SDK / iOS / web clients)."""
    if file_size <= _MIN_PART_SIZE:
        return _MIN_PART_SIZE
    if file_size < 100 * 1024 * 1024:
        target = max(1, file_size // _MIN_PART_SIZE)
    elif file_size < 1024**3:
        target = 50
    elif file_size < 10 * 1024**3:
        target = 100
    else:
        target = 200
    proposed = math.ceil(file_size / target)
    required = math.ceil(file_size / _MAX_PARTS)
    return max(_MIN_PART_SIZE, proposed, required)


def _kind(extension: str) -> str:
    if extension in _IMAGE_EXTS:
        return "Image"
    if extension in _VIDEO_EXTS:
        return "Video"
    return "File"


def _plan_file(index: int, spec: dict) -> dict:
    """Validate one entry of ``files`` and build its asset-create payload."""
    path = spec.get("path")
    name = spec.get("name") or (PurePath(path).name if path else None)
    label = f"files[{index}]" + (f" ({name})" if name else "")
    if not name:
        raise ValueError(f"{label}: pass `path` (the file on your computer) or `name`.")

    try:
        size = int(spec.get("size") or 0)
    except (TypeError, ValueError):
        size = 0
    if size <= 0:
        raise ValueError(
            f"{label}: `size` in bytes is required "
            "(macOS: stat -f%z FILE, Linux: stat -c%s FILE)."
        )

    extension = (
        (spec.get("extension") or PurePath(path or name).suffix).lstrip(".").lower()
    )
    if not extension:
        raise ValueError(f"{label}: the file needs an extension (or pass `extension`).")

    kind = spec.get("type") or _kind(extension)
    if kind not in ("Image", "Video", "File"):
        raise ValueError(f"{label}: `type` must be Image, Video or File.")

    part_size = _part_size(size)
    # `$type` MUST be the first property: the backend's polymorphic JSON
    # reader (.NET 8) only accepts the discriminator in first position.
    asset: dict = {
        "$type": kind,
        "name": name,
        "extension": extension,
        "memorySizeInBytes": size,
        "uploadPartSizeInBytes": part_size,
        "readOnly": False,
    }
    if kind == "Image":
        width, height = spec.get("width"), spec.get("height")
        if not width or not height or float(width) <= 0 or float(height) <= 0:
            raise ValueError(
                f"{label}: images need `width` and `height` in pixels "
                "(macOS: sips -g pixelWidth -g pixelHeight FILE)."
            )
        asset["width"] = float(width)
        asset["height"] = float(height)

    return {
        "asset": asset,
        "local_path": path or name,
        "size": size,
        "part_size": part_size,
    }


_SCRIPT_HEAD = """\
#!/usr/bin/env bash
# SRG+ direct upload (generated by create_upload). PUTs each file straight to
# storage and prints ONE JSON line: pass it as `uploads` to complete_upload.
# Needs bash, curl and dd. Re-running is safe (a part PUT just overwrites).
set -uo pipefail
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
up() { # up INDEX FILE ASSET_ID UPLOAD_ID PART_SIZE URL...
  local i="$1" f="$2" a="$3" u="$4" ps="$5"; shift 5
  [ -f "$f" ] || { echo "srgplus: no such file: $f" >&2; return 1; }
  local n=0 parts="" src tag
  for url in "$@"; do
    n=$((n + 1)); src="$f"
    if [ "$#" -gt 1 ]; then
      src="$T/$i.part"
      dd if="$f" of="$src" bs="$ps" skip=$((n - 1)) count=1 2>/dev/null || return 1
    fi
    tag="$(curl -sS -f --retry 3 --retry-delay 2 -X PUT -T "$src" \\
      -H 'Content-Type: application/octet-stream' -D - -o /dev/null "$url" \\
      | tr -d '\\r' | awk 'tolower($1)=="etag:"{gsub(/"/,"",$2); t=$2} END{print t}')"
    [ -n "$tag" ] || { echo "srgplus: upload failed: $f (part $n)" >&2; return 1; }
    parts="$parts${parts:+,}{\\"part_number\\":$n,\\"etag\\":\\"$tag\\"}"
  done
  printf '{"asset_id":"%s","upload_id":"%s","parts":[%s]}\\n' "$a" "$u" "$parts" \\
    > "$T/$(printf %05d "$i").json"
}
pids=""
run() {
  while [ "$(jobs -rp | wc -l | tr -d ' ')" -ge __PARALLEL__ ]; do sleep 0.2; done
  up "$@" & pids="$pids $!"
}
"""

_SCRIPT_TAIL = """\
fail=0; for p in $pids; do wait "$p" || fail=1; done
printf '['; cat "$T"/*.json 2>/dev/null | paste -sd, - | tr -d '\\n'; printf ']\\n'
[ "$fail" = 0 ] || { echo "srgplus: some files failed (above); re-run the script, then complete_upload" >&2; exit 1; }
"""


def _script(entries: list[dict]) -> str:
    lines = [_SCRIPT_HEAD.replace("__PARALLEL__", str(_SCRIPT_PARALLEL_FILES))]
    for i, e in enumerate(entries, 1):
        args = [
            str(i),
            e["local_path"],
            e["asset_id"],
            e["upload_id"],
            str(e["part_size"]),
            *e["urls"],
        ]
        lines.append("run " + " ".join(shlex.quote(a) for a in args) + "\n")
    lines.append(_SCRIPT_TAIL)
    return "".join(lines)


@mcp.tool(
    annotations=ToolAnnotations(
        title="Create upload (presigned URLs, no base64)",
        readOnlyHint=False,
        destructiveHint=False,
        openWorldHint=True,
    )
)
def create_upload(
    hub_profile_id: str,
    workspace_id: str,
    files: list[dict],
    output: str = "script",
) -> dict:
    """Upload files FROM THE USER'S COMPUTER into a hub's Drive — no base64.

    Step 1 of 3. Registers the files and returns presigned PUT URLs; the bytes
    go straight from the user's machine to storage (never through this server
    or the model). Then: run the returned `script` locally (step 2), and pass
    the JSON line it prints to complete_upload (step 3). Up to 100 files per
    call; images, videos (large files are split into parts) and other files.

    workspace_id: target workspace ID — get available IDs from list_workspaces()
    files: one object per file:
        {"path": "/Users/me/Covers/Reel 01.jpg",   # local path, used by the script
         "size": 312345,                           # bytes (required)
         "width": 1080, "height": 1920}            # pixels, required for images
      optional: "name" (display name, default = file name), "type"
      ("Image" | "Video" | "File", default from the extension), "extension".
      Get sizes and image dimensions for a folder on macOS with:
        for f in *.jpg; do printf '{"path":"%s","size":%s,"width":%s,"height":%s}\\n' \\
          "$PWD/$f" "$(stat -f%z "$f")" \\
          "$(sips -g pixelWidth "$f" | awk '/pixelWidth/{print $2}')" \\
          "$(sips -g pixelHeight "$f" | awk '/pixelHeight/{print $2}')"; done
      (Linux: stat -c%s FILE; identify -format '%w %h' FILE.)
    output: "script" (default) — a bash script (curl) that uploads everything
        and prints the JSON for complete_upload; run it with `bash`, e.g.
        save it to /tmp/srg_upload.sh and run `bash /tmp/srg_upload.sh`.
      "urls" — no script; each upload lists its part URLs instead. For each
        part: curl -sS -f -X PUT -T PART_FILE -D - -o /dev/null "URL" and keep
        the ETag response header (without quotes); files over one part are
        split at part_size bytes (the last part is shorter).

    Returns {"uploads": [{asset_id, upload_id, name, path, size, part_count}],
    "script": "..."}. URLs are valid 24 h; uploads not completed within 24 h
    are discarded.
    """
    if not files:
        raise ValueError("Pass at least one file.")
    if output not in ("script", "urls"):
        raise ValueError('`output` must be "script" or "urls".')
    plans = [_plan_file(i, spec) for i, spec in enumerate(files, 1)]

    inits: list[dict] = []
    for start in range(0, len(plans), _BATCH_LIMIT):
        chunk = plans[start : start + _BATCH_LIMIT]
        data = _raw.call(
            workspace_id,
            "POST",
            "/api/v1/assets/batch",
            json={"hubProfileId": hub_profile_id, "assets": [p["asset"] for p in chunk]},
        )
        if not isinstance(data, list) or len(data) != len(chunk):
            raise RuntimeError(
                f"SRG+ returned {len(data) if isinstance(data, list) else 'no'} upload "
                f"records for {len(chunk)} files; nothing was uploaded, retry."
            )
        inits.extend(data)

    entries = []
    for plan, init in zip(plans, inits, strict=True):
        entries.append(
            {
                **plan,
                "asset_id": init["id"],
                "upload_id": init["uploadId"],
                "urls": list(init.get("urls") or []),
            }
        )

    uploads = []
    for e in entries:
        row = {
            "asset_id": e["asset_id"],
            "upload_id": e["upload_id"],
            "name": e["asset"]["name"],
            "path": e["local_path"],
            "size": e["size"],
            "part_count": len(e["urls"]),
        }
        if output == "urls":
            row["part_size"] = e["part_size"]
            row["parts"] = [
                {
                    "part_number": n,
                    "url": url,
                    "length": min(e["part_size"], e["size"] - (n - 1) * e["part_size"]),
                }
                for n, url in enumerate(e["urls"], 1)
            ]
        uploads.append(row)

    result: dict = {"uploads": uploads}
    if output == "script":
        result["script"] = _script(entries)
        result["next"] = (
            "Run `script` with bash on the user's computer (it needs the files at "
            "`path`). It prints one JSON line; pass it unchanged as `uploads` to "
            "complete_upload(workspace_id, uploads=...)."
        )
    else:
        result["next"] = (
            "PUT each part to its URL, then call complete_upload(workspace_id, "
            'uploads=[{"asset_id","upload_id","parts":[{"part_number","etag"}]}]).'
        )
    return result


def _complete_one(workspace_id: str, upload: dict) -> dict:
    asset_id = upload.get("asset_id") or upload.get("id")
    upload_id = upload.get("upload_id")
    parts = upload.get("parts") or []
    if not asset_id or not upload_id or not parts:
        return {
            "asset_id": asset_id,
            "status": "failed",
            "error": "each upload needs asset_id, upload_id and parts[{part_number, etag}]",
        }
    tags = [
        {"partNumber": int(p["part_number"]), "eTag": str(p["etag"]).strip().strip('"')}
        for p in sorted(parts, key=lambda p: int(p["part_number"]))
    ]
    try:
        _raw.call(
            workspace_id,
            "POST",
            "/api/v1/files/upload/complete",
            json={"nodeId": asset_id, "uploadId": upload_id, "partTags": tags},
        )
        status = "completed"
    except srg.exceptions.ConflictError:
        # The backend answers 409 when the upload was already completed.
        status = "already_completed"
    except srg.exceptions.APIStatusError as exc:
        return {"asset_id": asset_id, "status": "failed", "error": exc.message}

    row: dict = {"asset_id": asset_id, "status": status}
    try:
        asset = _raw.call(workspace_id, "GET", f"/api/v1/assets/{asset_id}") or {}
    except srg.exceptions.APIStatusError:
        return row
    row.update(
        {
            "name": asset.get("name"),
            "type": asset.get("$type"),
            "size": asset.get("memorySizeInBytes"),
        }
    )
    if asset.get("width"):
        row["width"], row["height"] = asset.get("width"), asset.get("height")
    return row


@mcp.tool(
    annotations=ToolAnnotations(
        title="Complete upload",
        readOnlyHint=False,
        destructiveHint=False,
        openWorldHint=True,
    )
)
def complete_upload(workspace_id: str, uploads: list[dict]) -> dict:
    """Finish uploads started with create_upload → ready assets in the hub Drive.

    Step 3 of 3. Pass the JSON line printed by the create_upload script
    unchanged: [{"asset_id", "upload_id", "parts": [{"part_number", "etag"}]}].
    Safe to repeat: an upload that is already complete is reported as
    "already_completed". Then use the asset ids with set_cover / set_covers
    (images) or in a Media widget (videos, once they finish processing).

    workspace_id: target workspace ID — get available IDs from list_workspaces()
    Returns {"assets": [{asset_id, status, name, type, size, ...}],
    "completed": n, "failed": n}.
    """
    if not uploads:
        raise ValueError("Pass the uploads JSON printed by the create_upload script.")
    with ThreadPoolExecutor(max_workers=_API_WORKERS) as pool:
        rows = list(pool.map(lambda u: _complete_one(workspace_id, u), uploads))
    failed = sum(1 for r in rows if r["status"] == "failed")
    return {"assets": rows, "completed": len(rows) - failed, "failed": failed}


def _hub_of(content_id: str, workspace_id: str) -> str:
    return get_client().contents.get_v2(content_id, workspace_id=workspace_id).hub_profile_id


def _still_uploading(exc: srg.exceptions.APIStatusError) -> bool:
    return isinstance(exc, srg.exceptions.BadRequestError) and (
        "still uploading" in f"{exc.message} {exc.body}".lower()
    )


def set_cover_from_asset(
    workspace_id: str,
    hub_profile_id: str,
    content_id: str,
    asset_id: str,
    expected_version: int | None = None,
) -> None:
    """POST .../cover/from-asset, waiting out the post-upload "still uploading" window."""
    headers = (
        None if expected_version is None else {"If-Match": f'"{int(expected_version)}"'}
    )
    delays = iter(_STILL_UPLOADING_RETRY_DELAYS)
    while True:
        try:
            _raw.call(
                workspace_id,
                "POST",
                f"/api/v1/contents/{content_id}/cover/from-asset",
                json={"coverAssetId": asset_id},
                params={"hubProfileId": hub_profile_id},
                headers=headers,
            )
            return
        except srg.exceptions.APIStatusError as exc:
            delay = next(delays, None)
            if delay is None or not _still_uploading(exc):
                raise
            time.sleep(delay)


@mcp.tool(
    annotations=ToolAnnotations(
        title="Set cover from a Drive image",
        readOnlyHint=False,
        destructiveHint=False,
        openWorldHint=True,
    )
)
def set_cover(
    content_id: str,
    asset_id: str,
    workspace_id: str,
    hub_profile_id: str | None = None,
    expected_version: int | None = None,
) -> dict:
    """Use an image that is already in the hub Drive as a content's cover.

    asset_id: an Image asset of the same hub — e.g. from complete_upload or
        list_drive_files. The image bytes are copied into the cover, so the
        cover stays even if the Drive file is deleted later. Right after an
        upload the image may need a few seconds to be ready; this tool waits.
    hub_profile_id: owning hub; resolved from the content when omitted.
    expected_version: optional `version` from get_content_v2 — the cover is
        set only if the content did not change since; else 409.
    workspace_id: target workspace ID — get available IDs from list_workspaces()
    For many covers at once use set_covers.
    """
    hub = hub_profile_id or _hub_of(content_id, workspace_id)
    set_cover_from_asset(workspace_id, hub, content_id, asset_id, expected_version)
    return {"content_id": content_id, "asset_id": asset_id, "status": "cover_set"}


@mcp.tool(
    annotations=ToolAnnotations(
        title="Set many covers from Drive images",
        readOnlyHint=False,
        destructiveHint=False,
        openWorldHint=True,
    )
)
def set_covers(
    items: list[dict],
    workspace_id: str,
    hub_profile_id: str | None = None,
) -> dict:
    """Set covers on many contents in one call, each from a Drive image.

    items: [{"content_id": "...", "asset_id": "..."}, ...] (up to 100); an
        item may add "expected_version" (from get_content_v2) → 409 if stale.
    hub_profile_id: pass it when all contents are in one hub (saves a lookup
        per item); otherwise each content's hub is resolved automatically.
    workspace_id: target workspace ID — get available IDs from list_workspaces()
    A failure on one item does not stop the others. Returns
    {"results": [{content_id, asset_id, status | error}], "set": n, "failed": n}.
    """
    if not items:
        raise ValueError("Pass at least one {content_id, asset_id} item.")
    if len(items) > 100:
        raise ValueError("At most 100 covers per call; split the list.")

    def one(item: dict) -> dict:
        content_id, asset_id = item.get("content_id"), item.get("asset_id")
        if not content_id or not asset_id:
            return {**item, "status": "failed", "error": "needs content_id and asset_id"}
        try:
            hub = hub_profile_id or _hub_of(content_id, workspace_id)
            set_cover_from_asset(
                workspace_id, hub, content_id, asset_id, item.get("expected_version")
            )
        except srg.exceptions.SRGError as exc:
            return {
                "content_id": content_id,
                "asset_id": asset_id,
                "status": "failed",
                "error": exc.message,
            }
        return {"content_id": content_id, "asset_id": asset_id, "status": "cover_set"}

    with ThreadPoolExecutor(max_workers=_API_WORKERS) as pool:
        results = list(pool.map(one, items))
    failed = sum(1 for r in results if r["status"] == "failed")
    return {"results": results, "set": len(results) - failed, "failed": failed}


_DRIVE_TYPES = ("Image", "Video", "File", "Audio", "Document", "Media", "Embed", "Other")


def _drive_row(item: dict) -> dict:
    row = {
        "id": item.get("id"),
        "name": item.get("name"),
        "type": item.get("$type"),
        "extension": item.get("extension"),
        "size": item.get("memorySizeInBytes"),
    }
    if item.get("width"):
        row["width"], row["height"] = item.get("width"), item.get("height")
    if item.get("status"):
        row["status"] = item.get("status")
    return row


@mcp.tool(
    annotations=ToolAnnotations(
        title="List Drive files",
        readOnlyHint=True,
        destructiveHint=False,
        openWorldHint=True,
    )
)
def list_drive_files(
    hub_profile_id: str,
    workspace_id: str,
    types: list[str] | None = None,
    search: str | None = None,
    page_size: int = 50,
    cursor: str | None = None,
) -> dict:
    """List the files in a hub's Drive as compact rows: id, name, type,
    extension, size (bytes), width/height (images), status (videos).

    types: filter, e.g. ["Image"] or ["Video"]. Values: Image, Video, File,
        Audio, Document, Media, Embed, Other. Default: all.
    search: optional keyword (matches names); without it the list is paged
        with `cursor` (pass the returned cursor for the next page).
    workspace_id: target workspace ID — get available IDs from list_workspaces()
    A file appears a few seconds after complete_upload. The Drive has no
    folders. For a file's signed download URL (valid ~7 days) call get_asset.
    """
    bad = [t for t in (types or []) if t not in _DRIVE_TYPES]
    if bad:
        raise ValueError(f"Unknown type(s) {bad}; use {list(_DRIVE_TYPES)}.")
    if search:
        data = _raw.call(
            workspace_id,
            "POST",
            f"/api/v1/assets/{hub_profile_id}/search",
            json={"search": search, "type": types or []},
        )
        items = data if isinstance(data, list) else []
        return {"items": [_drive_row(i) for i in items], "cursor": None}

    body: dict = {
        "pageSize": max(1, min(page_size, 200)),
        "onlyArchived": False,
        "excludeCollections": [],
        "excludeAssets": [],
        "type": types or [],
    }
    if cursor:
        body["cursor"] = cursor
    data = _raw.call(
        workspace_id, "POST", f"/api/v1/assets/{hub_profile_id}/filter/", json=body
    ) or {}
    return {
        "items": [_drive_row(i) for i in data.get("items") or []],
        "cursor": data.get("cursor"),
    }
